// 由 scripts/build-blocks.mts 从 assets/chem/building-blocks.json 生成，不要手改。
// 重新生成：npm run build:blocks

export type BuildingBlock = {
  name: string;
  canonical: string;
  inchiKey: string;
  category: string;
};

export const BUILDING_BLOCK_VERSION = "2026-09-05";

export const BUILDING_BLOCKS: BuildingBlock[] = [
  { name: "苯", canonical: "c1ccccc1", inchiKey: "UHOVQNZJYSORNB-UHFFFAOYSA-N", category: "arene" },
  { name: "甲苯", canonical: "Cc1ccccc1", inchiKey: "YXFVVABEGXRONW-UHFFFAOYSA-N", category: "arene" },
  { name: "苯甲醛", canonical: "O=Cc1ccccc1", inchiKey: "HUMNYLRZRPPJDN-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "苯乙酮", canonical: "CC(=O)c1ccccc1", inchiKey: "KWOLFJPFCHCOCG-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "二苯甲酮", canonical: "O=C(c1ccccc1)c1ccccc1", inchiKey: "RWCCWEUUXYIKHB-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "苯甲酸", canonical: "O=C(O)c1ccccc1", inchiKey: "WPYMKLBDIGXBTP-UHFFFAOYSA-N", category: "acid" },
  { name: "苯甲酸甲酯", canonical: "COC(=O)c1ccccc1", inchiKey: "QPJVMBTYPHYUOC-UHFFFAOYSA-N", category: "ester" },
  { name: "苯甲酰氯", canonical: "O=C(Cl)c1ccccc1", inchiKey: "PASDCCFISLVPSO-UHFFFAOYSA-N", category: "acyl halide" },
  { name: "苯酚", canonical: "Oc1ccccc1", inchiKey: "ISWSIDIOOBJBQZ-UHFFFAOYSA-N", category: "phenol" },
  { name: "苯胺", canonical: "Nc1ccccc1", inchiKey: "PAYRUJLWNCNPSJ-UHFFFAOYSA-N", category: "amine" },
  { name: "苄醇", canonical: "OCc1ccccc1", inchiKey: "WVDDGKGOMKODPV-UHFFFAOYSA-N", category: "alcohol" },
  { name: "苄胺", canonical: "NCc1ccccc1", inchiKey: "WGQKYBSKWIADBV-UHFFFAOYSA-N", category: "amine" },
  { name: "苄氯", canonical: "ClCc1ccccc1", inchiKey: "KCXMKQUNVWSEMD-UHFFFAOYSA-N", category: "halide" },
  { name: "苄溴", canonical: "BrCc1ccccc1", inchiKey: "AGEZXYOZHKGVCM-UHFFFAOYSA-N", category: "halide" },
  { name: "溴苯", canonical: "Brc1ccccc1", inchiKey: "QARVLSVVCXYDNA-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "碘苯", canonical: "Ic1ccccc1", inchiKey: "SNHMUERNLJLMHN-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "氯苯", canonical: "Clc1ccccc1", inchiKey: "MVPPADPHJFYWMZ-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-溴甲苯", canonical: "Cc1ccc(Br)cc1", inchiKey: "ZBTMRBYMKUEVEU-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-溴苯甲醛", canonical: "O=Cc1ccc(Br)cc1", inchiKey: "ZRYZBQLXDKPBDU-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-溴苯甲酸", canonical: "O=C(O)c1ccc(Br)cc1", inchiKey: "TUXYZHVUPGXXQG-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-溴苯胺", canonical: "Nc1ccc(Br)cc1", inchiKey: "WDFQBORIUYODSI-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-溴苯酚", canonical: "Oc1ccc(Br)cc1", inchiKey: "GZFGOTFRPZRKDS-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-溴苯乙酮", canonical: "CC(=O)c1ccc(Br)cc1", inchiKey: "WYECURVXVYPVAT-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-溴硝基苯", canonical: "O=[N+]([O-])c1ccc(Br)cc1", inchiKey: "ZDFBKZUDCQQKAC-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-溴苯甲腈", canonical: "N#Cc1ccc(Br)cc1", inchiKey: "HQSCPPCMBMFJJN-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-溴苯甲醚", canonical: "COc1ccc(Br)cc1", inchiKey: "QJPJQTDYNZXKQF-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "2-溴吡啶", canonical: "Brc1ccccn1", inchiKey: "IMRWILPUOVGIMU-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "3-溴吡啶", canonical: "Brc1cccnc1", inchiKey: "NYPYPOZNGOXYSU-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "2-氯吡啶", canonical: "Clc1ccccn1", inchiKey: "OKDGRDCXVWSXDC-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "2,6-二氯吡啶", canonical: "Clc1cccc(Cl)n1", inchiKey: "FILKGCRCWDMBKA-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "2-氯嘧啶", canonical: "Clc1ncccn1", inchiKey: "UNCQVRBWJWWJBF-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "2,4-二氯嘧啶", canonical: "Clc1ccnc(Cl)n1", inchiKey: "BTTNYQZNBZNDOR-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "5-溴嘧啶", canonical: "Brc1cncnc1", inchiKey: "GYCPLYCTMDTEPU-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "2-溴噻吩", canonical: "Brc1cccs1", inchiKey: "TUCRZHGAIRVWTI-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "3-溴噻吩", canonical: "Brc1ccsc1", inchiKey: "XCMISAPCWHTVNG-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "2-溴呋喃", canonical: "Brc1ccco1", inchiKey: "OYMCMWPHMPODNK-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "5-溴吲哚", canonical: "Brc1ccc2[nH]ccc2c1", inchiKey: "VXWVFZFZYXOBTA-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "4-溴-1H-吡唑", canonical: "Brc1cn[nH]c1", inchiKey: "WVGCPEDBFHEHEZ-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "苯硼酸", canonical: "OB(O)c1ccccc1", inchiKey: "HXITXNWTGFUOAU-UHFFFAOYSA-N", category: "boron" },
  { name: "4-甲基苯硼酸", canonical: "Cc1ccc(B(O)O)cc1", inchiKey: "BIWQNIMLAISTBV-UHFFFAOYSA-N", category: "boron" },
  { name: "4-甲氧基苯硼酸", canonical: "COc1ccc(B(O)O)cc1", inchiKey: "VOAAEKKFGLPLLU-UHFFFAOYSA-N", category: "boron" },
  { name: "4-氟苯硼酸", canonical: "OB(O)c1ccc(F)cc1", inchiKey: "LBUNNMJLXWQQBY-UHFFFAOYSA-N", category: "boron" },
  { name: "4-氯苯硼酸", canonical: "OB(O)c1ccc(Cl)cc1", inchiKey: "CAYQIZIAYYNFCS-UHFFFAOYSA-N", category: "boron" },
  { name: "4-甲酰基苯硼酸", canonical: "O=Cc1ccc(B(O)O)cc1", inchiKey: "VXWBQOJISHAKKM-UHFFFAOYSA-N", category: "boron" },
  { name: "3-吡啶硼酸", canonical: "OB(O)c1cccnc1", inchiKey: "ABMYEXAYWZJVOV-UHFFFAOYSA-N", category: "boron" },
  { name: "噻吩-2-硼酸", canonical: "OB(O)c1cccs1", inchiKey: "ARYHTUPFQTUBBG-UHFFFAOYSA-N", category: "boron" },
  { name: "联硼酸频那醇酯 B2pin2", canonical: "CC1(C)OB(B2OC(C)(C)C(C)(C)O2)OC1(C)C", inchiKey: "IPWKHHSGDUIRAH-UHFFFAOYSA-N", category: "boron" },
  { name: "苯硼酸频那醇酯", canonical: "CC1(C)OB(c2ccccc2)OC1(C)C", inchiKey: "KKLCYBZPQDOFQK-UHFFFAOYSA-N", category: "boron" },
  { name: "甲醇", canonical: "CO", inchiKey: "OKKJLVBELUTLKV-UHFFFAOYSA-N", category: "solvent/alcohol" },
  { name: "乙醇", canonical: "CCO", inchiKey: "LFQSCWFLJHTTHZ-UHFFFAOYSA-N", category: "solvent/alcohol" },
  { name: "异丙醇", canonical: "CC(C)O", inchiKey: "KFZMGEQAYNKOFK-UHFFFAOYSA-N", category: "solvent/alcohol" },
  { name: "叔丁醇", canonical: "CC(C)(C)O", inchiKey: "DKGAVHZHDRPRBM-UHFFFAOYSA-N", category: "alcohol" },
  { name: "乙二醇", canonical: "OCCO", inchiKey: "LYCAIKOWRPUZTN-UHFFFAOYSA-N", category: "alcohol" },
  { name: "丙酮", canonical: "CC(C)=O", inchiKey: "CSCPPACGZOOCGX-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "乙醛", canonical: "CC=O", inchiKey: "IKHGUXGNUITLKF-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "多聚甲醛/甲醛", canonical: "C=O", inchiKey: "WSFSSNUMVMOOMR-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "乙酸", canonical: "CC(=O)O", inchiKey: "QTBSBXVTEAMEQO-UHFFFAOYSA-N", category: "acid" },
  { name: "乙酸酐", canonical: "CC(=O)OC(C)=O", inchiKey: "WFDIJRYMOXRFFG-UHFFFAOYSA-N", category: "acylating" },
  { name: "乙酰氯", canonical: "CC(=O)Cl", inchiKey: "WETWJCDKMRHUPV-UHFFFAOYSA-N", category: "acyl halide" },
  { name: "乙酸乙酯", canonical: "CCOC(C)=O", inchiKey: "XEKOWRVHYACXOJ-UHFFFAOYSA-N", category: "ester" },
  { name: "丙烯酸甲酯", canonical: "C=CC(=O)OC", inchiKey: "BAPJBEWLBFYGME-UHFFFAOYSA-N", category: "Michael acceptor" },
  { name: "丙烯酸乙酯", canonical: "C=CC(=O)OCC", inchiKey: "JIGUQPWFLRLWPJ-UHFFFAOYSA-N", category: "Michael acceptor" },
  { name: "丙烯腈", canonical: "C=CC#N", inchiKey: "NLHHRLWOUZZQLW-UHFFFAOYSA-N", category: "Michael acceptor" },
  { name: "甲基乙烯基酮", canonical: "C=CC(C)=O", inchiKey: "FUSUHKVFWTUUBE-UHFFFAOYSA-N", category: "Michael acceptor" },
  { name: "丙二酸二乙酯", canonical: "CCOC(=O)CC(=O)OCC", inchiKey: "IYXGSMUGOJNHAZ-UHFFFAOYSA-N", category: "1,3-dicarbonyl" },
  { name: "乙酰乙酸乙酯", canonical: "CCOC(=O)CC(C)=O", inchiKey: "XYIBRDXRRQCHLP-UHFFFAOYSA-N", category: "1,3-dicarbonyl" },
  { name: "乙酰丙酮", canonical: "CC(=O)CC(C)=O", inchiKey: "YRKCREAYFQTBPV-UHFFFAOYSA-N", category: "1,3-dicarbonyl" },
  { name: "丙二腈", canonical: "N#CCC#N", inchiKey: "CUONGYYJJVDODC-UHFFFAOYSA-N", category: "1,3-dicarbonyl" },
  { name: "碘甲烷", canonical: "CI", inchiKey: "INQOMBQAUSQDDS-UHFFFAOYSA-N", category: "alkyl halide" },
  { name: "溴乙烷", canonical: "CCBr", inchiKey: "RDHPKYGYEGBMSE-UHFFFAOYSA-N", category: "alkyl halide" },
  { name: "1-溴丁烷", canonical: "CCCCBr", inchiKey: "MPPPKRYCTPRNTB-UHFFFAOYSA-N", category: "alkyl halide" },
  { name: "1,2-二溴乙烷", canonical: "BrCCBr", inchiKey: "PAAZPARNPHGIKF-UHFFFAOYSA-N", category: "alkyl halide" },
  { name: "1,3-二溴丙烷", canonical: "BrCCCBr", inchiKey: "VEFLKXRACNJHOV-UHFFFAOYSA-N", category: "alkyl halide" },
  { name: "溴乙酸乙酯", canonical: "CCOC(=O)CBr", inchiKey: "PQJJJMRNHATNKG-UHFFFAOYSA-N", category: "alkyl halide" },
  { name: "氯乙酰氯", canonical: "O=C(Cl)CCl", inchiKey: "VGCXGMAHQTYDJK-UHFFFAOYSA-N", category: "acyl halide" },
  { name: "环己酮", canonical: "O=C1CCCCC1", inchiKey: "JHIVVAPYMSGYDF-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "环戊酮", canonical: "O=C1CCCC1", inchiKey: "BGTOWKSIORTVQH-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "环己烯酮", canonical: "O=C1C=CCCC1", inchiKey: "FWFSEYBSWVRWGL-UHFFFAOYSA-N", category: "Michael acceptor" },
  { name: "环己烷", canonical: "C1CCCCC1", inchiKey: "XDTMQSROBMDMFD-UHFFFAOYSA-N", category: "alkane" },
  { name: "环己醇", canonical: "OC1CCCCC1", inchiKey: "HPXRVTGHNJAIIH-UHFFFAOYSA-N", category: "alcohol" },
  { name: "环丙胺", canonical: "NC1CC1", inchiKey: "HTJDQJBWANPRPF-UHFFFAOYSA-N", category: "amine" },
  { name: "环丙基溴", canonical: "BrC1CC1", inchiKey: "LKXYJYDRLBPHRS-UHFFFAOYSA-N", category: "alkyl halide" },
  { name: "吗啉", canonical: "C1COCCN1", inchiKey: "YNAVUWVOSKDBBP-UHFFFAOYSA-N", category: "amine" },
  { name: "哌啶", canonical: "C1CCNCC1", inchiKey: "NQRYJNQNLNOLGT-UHFFFAOYSA-N", category: "amine" },
  { name: "哌嗪", canonical: "C1CNCCN1", inchiKey: "GLUUGHFHXGJENI-UHFFFAOYSA-N", category: "amine" },
  { name: "N-Boc-哌嗪", canonical: "CC(C)(C)OC(=O)N1CCNCC1", inchiKey: "CWXPZXBSDSIRCS-UHFFFAOYSA-N", category: "amine" },
  { name: "吡咯烷", canonical: "C1CCNC1", inchiKey: "RWRDLPDLKQPQOW-UHFFFAOYSA-N", category: "amine" },
  { name: "二乙胺", canonical: "CCNCC", inchiKey: "HPNMFZURTQLUMO-UHFFFAOYSA-N", category: "amine" },
  { name: "三乙胺", canonical: "CCN(CC)CC", inchiKey: "ZMANZCXQSJIPKH-UHFFFAOYSA-N", category: "base" },
  { name: "二异丙基乙胺 DIPEA", canonical: "CCN(C(C)C)C(C)C", inchiKey: "JGFZNNIVVJXRND-UHFFFAOYSA-N", category: "base" },
  { name: "吡啶", canonical: "c1ccncc1", inchiKey: "JUJWROOIHBZHMG-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "DMAP", canonical: "CN(C)c1ccncc1", inchiKey: "VHYFNPMBLIVWCW-UHFFFAOYSA-N", category: "catalyst" },
  { name: "咪唑", canonical: "c1c[nH]cn1", inchiKey: "RAXXELZNTBOGNW-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "吡唑", canonical: "c1cn[nH]c1", inchiKey: "WTKZEGDFNFYCGP-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "1-甲基吡唑", canonical: "Cn1cccn1", inchiKey: "UQFQONCQIQEYPJ-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "噻唑", canonical: "c1cscn1", inchiKey: "FZWLAAWBMGSTSO-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "噁唑", canonical: "c1cocn1", inchiKey: "ZCQWOFVYLHDMMC-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "吲哚", canonical: "c1ccc2[nH]ccc2c1", inchiKey: "SIKJAQJRHWYJAI-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "喹啉", canonical: "c1ccc2ncccc2c1", inchiKey: "SMWDFEZZVXVKRB-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "嘧啶", canonical: "c1cncnc1", inchiKey: "CZPWVGJYEJSRLH-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "呋喃", canonical: "c1ccoc1", inchiKey: "YLQBMQCUIZJEEH-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "噻吩", canonical: "c1ccsc1", inchiKey: "YTPLMLYBLZKORZ-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "苯并噻唑", canonical: "c1ccc2scnc2c1", inchiKey: "IOJUPLGTWVMSFF-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "苯并咪唑", canonical: "c1ccc2[nH]cnc2c1", inchiKey: "HYZJCKYKOHLVJF-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "甘氨酸", canonical: "NCC(=O)O", inchiKey: "DHMQDGOQFOQNFH-UHFFFAOYSA-N", category: "amino acid" },
  { name: "L-丙氨酸", canonical: "C[C@H](N)C(=O)O", inchiKey: "QNAYBMKLOCPYGJ-REOHCLBHSA-N", category: "amino acid" },
  { name: "L-脯氨酸", canonical: "O=C(O)[C@@H]1CCCN1", inchiKey: "ONIBWKKTOPOVIA-BYPYZUCNSA-N", category: "amino acid" },
  { name: "L-苯丙氨酸", canonical: "N[C@@H](Cc1ccccc1)C(=O)O", inchiKey: "COLNVLDHVKWLRT-QMMMGPOBSA-N", category: "amino acid" },
  { name: "L-缬氨酸", canonical: "CC(C)[C@H](N)C(=O)O", inchiKey: "KZSNJWFQEVHDMF-BYPYZUCNSA-N", category: "amino acid" },
  { name: "Boc酸酐 Boc2O", canonical: "CC(C)(C)OC(=O)OC(=O)OC(C)(C)C", inchiKey: "DYHSDKLCOJIUFX-UHFFFAOYSA-N", category: "protecting" },
  { name: "氯甲酸苄酯 Cbz-Cl", canonical: "O=C(Cl)OCc1ccccc1", inchiKey: "HSDAJNMJOMSNEV-UHFFFAOYSA-N", category: "protecting" },
  { name: "TBSCl", canonical: "CC(C)(C)[Si](C)(C)Cl", inchiKey: "BCNZYOJHNLTNEZ-UHFFFAOYSA-N", category: "protecting" },
  { name: "对甲苯磺酰氯 TsCl", canonical: "Cc1ccc(S(=O)(=O)Cl)cc1", inchiKey: "YYROPELSRYBVMQ-UHFFFAOYSA-N", category: "sulfonyl" },
  { name: "甲磺酰氯 MsCl", canonical: "CS(=O)(=O)Cl", inchiKey: "QARBMVPHQWIHKH-UHFFFAOYSA-N", category: "sulfonyl" },
  { name: "对甲苯磺酸 TsOH", canonical: "Cc1ccc(S(=O)(=O)O)cc1", inchiKey: "JOXIMZWYDAKGHI-UHFFFAOYSA-N", category: "acid" },
  { name: "三氟乙酸", canonical: "O=C(O)C(F)(F)F", inchiKey: "DTQVDTLACAAQTR-UHFFFAOYSA-N", category: "acid" },
  { name: "三氟甲磺酸酐", canonical: "O=S(=O)(OS(=O)(=O)C(F)(F)F)C(F)(F)F", inchiKey: "WJKHJLXJJJATHN-UHFFFAOYSA-N", category: "sulfonyl" },
  { name: "硼氢化钠", canonical: "[BH4-].[Na+]", inchiKey: "YOQDYZUWIQVZSF-UHFFFAOYSA-N", category: "reductant" },
  { name: "三乙酰氧基硼氢化钠", canonical: "CC(=O)O[BH-](OC(C)=O)OC(C)=O.[Na+]", inchiKey: "HHYFEYBWNZJVFQ-UHFFFAOYSA-N", category: "reductant" },
  { name: "氰基硼氢化钠", canonical: "B.[C-]#N.[Na+]", inchiKey: "PQFFEKIHLCWXQF-UHFFFAOYSA-N", category: "reductant" },
  { name: "碳酸钾", canonical: "O=C([O-])[O-].[K+].[K+]", inchiKey: "BWHMMNNQKKPAPP-UHFFFAOYSA-L", category: "base" },
  { name: "碳酸铯", canonical: "O=C([O-])[O-].[Cs+].[Cs+]", inchiKey: "FJDQFPXHSGXQBY-UHFFFAOYSA-L", category: "base" },
  { name: "叔丁醇钾", canonical: "CC(C)(C)[O-].[K+]", inchiKey: "LPNYRYFBWFDTMA-UHFFFAOYSA-N", category: "base" },
  { name: "氢化钠", canonical: "[H-].[Na+]", inchiKey: "BZKBCQXYZZXSCO-UHFFFAOYSA-N", category: "base" },
  { name: "苯乙烯", canonical: "C=Cc1ccccc1", inchiKey: "PPBRXRYQALVLMV-UHFFFAOYSA-N", category: "alkene" },
  { name: "苯乙炔", canonical: "C#Cc1ccccc1", inchiKey: "UEXCJVNBTNXOEH-UHFFFAOYSA-N", category: "alkyne" },
  { name: "三甲基硅乙炔", canonical: "C#C[Si](C)(C)C", inchiKey: "CWMFRHBXRUITQE-UHFFFAOYSA-N", category: "alkyne" },
  { name: "烯丙基溴", canonical: "C=CCBr", inchiKey: "BHELZAPQIKSEDF-UHFFFAOYSA-N", category: "alkyl halide" },
  { name: "丙炔溴", canonical: "C#CCBr", inchiKey: "YORCIIVHUBAYBQ-UHFFFAOYSA-N", category: "alkyl halide" },
  { name: "对苯二酚", canonical: "Oc1ccc(O)cc1", inchiKey: "QIGBRXMKCJKVMJ-UHFFFAOYSA-N", category: "phenol" },
  { name: "间苯二酚", canonical: "Oc1cccc(O)c1", inchiKey: "GHMLBKRAJCXXBS-UHFFFAOYSA-N", category: "phenol" },
  { name: "邻苯二胺", canonical: "Nc1ccccc1N", inchiKey: "GEYOCULIXLDCMW-UHFFFAOYSA-N", category: "amine" },
  { name: "对苯二胺", canonical: "Nc1ccc(N)cc1", inchiKey: "CBCKQZAAMUWICA-UHFFFAOYSA-N", category: "amine" },
  { name: "水杨醛", canonical: "O=Cc1ccccc1O", inchiKey: "SMQUZDBALVYZAC-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "邻苯二甲酸酐", canonical: "O=C1OC(=O)c2ccccc21", inchiKey: "LGRFSURHDFAFJT-UHFFFAOYSA-N", category: "anhydride" },
  { name: "马来酸酐", canonical: "O=C1C=CC(=O)O1", inchiKey: "FPYJFEHAWHCUMM-UHFFFAOYSA-N", category: "anhydride" },
  { name: "尿素", canonical: "NC(N)=O", inchiKey: "XSQUKJJJFZCRTK-UHFFFAOYSA-N", category: "misc" },
  { name: "硫脲", canonical: "NC(N)=S", inchiKey: "UMGDCJDMYOKAJW-UHFFFAOYSA-N", category: "misc" },
  { name: "肼", canonical: "NN", inchiKey: "OAKJQQAXSVQMHS-UHFFFAOYSA-N", category: "misc" },
  { name: "羟胺", canonical: "NO", inchiKey: "AVXURJPOCDRRFD-UHFFFAOYSA-N", category: "misc" },
  { name: "叠氮化钠", canonical: "[N-]=[N+]=[N-].[Na+]", inchiKey: "PXIPVTKHYLBLMZ-UHFFFAOYSA-N", category: "misc" },
  { name: "氰化钠", canonical: "[C-]#N.[Na+]", inchiKey: "MNWBNISUBARLIT-UHFFFAOYSA-N", category: "misc" },
  { name: "硝基甲烷", canonical: "C[N+](=O)[O-]", inchiKey: "LYGJENNIWJXYER-UHFFFAOYSA-N", category: "misc" },
  { name: "2-氨基吡啶", canonical: "Nc1ccccn1", inchiKey: "ICSNLGPSRYBMBD-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "4-氨基吡啶", canonical: "Nc1ccncc1", inchiKey: "NUKYPUAOHBNCPY-UHFFFAOYSA-N", category: "heteroarene" },
  { name: "烟酸", canonical: "O=C(O)c1cccnc1", inchiKey: "PVNIIMVLHYAWGP-UHFFFAOYSA-N", category: "heteroaryl acid" },
  { name: "异烟酸", canonical: "O=C(O)c1ccncc1", inchiKey: "TWBYWOBDOCUKOW-UHFFFAOYSA-N", category: "heteroaryl acid" },
  { name: "吡啶-2-甲醛", canonical: "O=Cc1ccccn1", inchiKey: "CSDSSGBPEUDDEE-UHFFFAOYSA-N", category: "heteroaryl carbonyl" },
  { name: "噻吩-2-甲醛", canonical: "O=Cc1cccs1", inchiKey: "CNUDBTRUORMMPA-UHFFFAOYSA-N", category: "heteroaryl carbonyl" },
  { name: "糠醛", canonical: "O=Cc1ccco1", inchiKey: "HYBBIBNJHNGZAN-UHFFFAOYSA-N", category: "heteroaryl carbonyl" },
  { name: "4-硝基苯甲醛", canonical: "O=Cc1ccc([N+](=O)[O-])cc1", inchiKey: "BXRFQSNOROATLV-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "4-甲氧基苯甲醛", canonical: "COc1ccc(C=O)cc1", inchiKey: "ZRSNZINYAWTAHE-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "肉桂醛", canonical: "O=CC=Cc1ccccc1", inchiKey: "KJPRLNWUNMBNBZ-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "查尔酮", canonical: "O=C(C=Cc1ccccc1)c1ccccc1", inchiKey: "DQFBYFPFKXHELB-UHFFFAOYSA-N", category: "Michael acceptor" },
  { name: "苯乙酸", canonical: "O=C(O)Cc1ccccc1", inchiKey: "WLJVXDMOQOGPHL-UHFFFAOYSA-N", category: "acid" },
  { name: "苯丙酸", canonical: "O=C(O)CCc1ccccc1", inchiKey: "XMIIGOLPHOKFCH-UHFFFAOYSA-N", category: "acid" },
  { name: "丙酸", canonical: "CCC(=O)O", inchiKey: "XBDQKXXYIPTUBI-UHFFFAOYSA-N", category: "acid" },
  { name: "丁酸", canonical: "CCCC(=O)O", inchiKey: "FERIUCNNQQJTOY-UHFFFAOYSA-N", category: "acid" },
  { name: "草酰氯", canonical: "O=C(Cl)C(=O)Cl", inchiKey: "CTSLXHKWHWQRSH-UHFFFAOYSA-N", category: "acyl halide" },
  { name: "异丁基氯甲酸酯", canonical: "CC(C)COC(=O)Cl", inchiKey: "YOETUEMZNOLGDB-UHFFFAOYSA-N", category: "activating" },
  { name: "EDCI", canonical: "CCN=C=NCCCN(C)C", inchiKey: "LMDZBCPBFSXMTL-UHFFFAOYSA-N", category: "coupling" },
  { name: "DCC", canonical: "C(=NC1CCCCC1)=NC1CCCCC1", inchiKey: "QOSSAOTZNIDXMA-UHFFFAOYSA-N", category: "coupling" },
  { name: "HATU", canonical: "CN(C)C(On1nnc2ccccc21)=[N+](C)C.F[P-](F)(F)(F)(F)F", inchiKey: "UQYZFNUUOSSNKT-UHFFFAOYSA-N", category: "coupling" },
  { name: "HOBt", canonical: "On1nnc2ccccc21", inchiKey: "ASOKPJOREAFHNY-UHFFFAOYSA-N", category: "coupling" },
  { name: "四氢呋喃", canonical: "C1CCOC1", inchiKey: "WYURNTSHIVDZCO-UHFFFAOYSA-N", category: "solvent" },
  { name: "二氯甲烷", canonical: "ClCCl", inchiKey: "YMWUJEATGCHHMB-UHFFFAOYSA-N", category: "solvent" },
  { name: "乙腈", canonical: "CC#N", inchiKey: "WEVYAHXRMPXWCK-UHFFFAOYSA-N", category: "solvent" },
  { name: "DMF", canonical: "CN(C)C=O", inchiKey: "ZMXDDKWLCZADIW-UHFFFAOYSA-N", category: "solvent" },
  { name: "DMSO", canonical: "CS(C)=O", inchiKey: "IAZDPXIOMUYVGZ-UHFFFAOYSA-N", category: "solvent" },
  { name: "1,4-二氧六环", canonical: "C1COCCO1", inchiKey: "RYHBNJHYFVUHQT-UHFFFAOYSA-N", category: "solvent" },
  { name: "甲苯磺酸甲酯", canonical: "COS(=O)(=O)c1ccc(C)cc1", inchiKey: "VUQUOGPMUUJORT-UHFFFAOYSA-N", category: "alkylating" },
  { name: "硫酸二甲酯", canonical: "COS(=O)(=O)OC", inchiKey: "VAYGXNSJCAHWJZ-UHFFFAOYSA-N", category: "alkylating" },
  { name: "4-氟硝基苯", canonical: "O=[N+]([O-])c1ccc(F)cc1", inchiKey: "WFQDTOYDVUWQMS-UHFFFAOYSA-N", category: "SNAr" },
  { name: "2-氟硝基苯", canonical: "O=[N+]([O-])c1ccccc1F", inchiKey: "PWKNBLFSJAVFAB-UHFFFAOYSA-N", category: "SNAr" },
  { name: "2,4-二氟硝基苯", canonical: "O=[N+]([O-])c1ccc(F)cc1F", inchiKey: "RJXOVESYJFXCGI-UHFFFAOYSA-N", category: "SNAr" },
  { name: "4-氯-3-硝基吡啶", canonical: "O=[N+]([O-])c1cnccc1Cl", inchiKey: "JOTRPRKONYTVBV-UHFFFAOYSA-N", category: "SNAr" },
  { name: "2-氯-5-硝基吡啶", canonical: "O=[N+]([O-])c1ccc(Cl)nc1", inchiKey: "BAZVFQBTJPBRTJ-UHFFFAOYSA-N", category: "SNAr" },
  { name: "4-氯喹啉", canonical: "Clc1ccnc2ccccc12", inchiKey: "KNDOFJFSHZCKGT-UHFFFAOYSA-N", category: "SNAr" },
  { name: "2,4-二氯喹唑啉", canonical: "Clc1nc(Cl)c2ccccc2n1", inchiKey: "TUQSVSYUEBNNKQ-UHFFFAOYSA-N", category: "SNAr" },
  { name: "6-溴喹啉", canonical: "Brc1ccc2ncccc2c1", inchiKey: "IFIHYLCUKYCKRH-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "5-溴-2-氯吡啶", canonical: "Clc1ccc(Br)cn1", inchiKey: "PEAOEIWYQVXZMB-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "3-溴-5-氯吡啶", canonical: "Clc1cncc(Br)c1", inchiKey: "BELDOPUBSLPBCQ-UHFFFAOYSA-N", category: "heteroaryl halide" },
  { name: "1,4-二溴苯", canonical: "Brc1ccc(Br)cc1", inchiKey: "SWJPEBQEEAHIGZ-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "1,3-二溴苯", canonical: "Brc1cccc(Br)c1", inchiKey: "JSRLURSZEMLAFO-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-碘苯甲醚", canonical: "COc1ccc(I)cc1", inchiKey: "SYSZENVIJHPFNL-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "4-碘苯甲酸", canonical: "O=C(O)c1ccc(I)cc1", inchiKey: "GHICCUXQJBDNRN-UHFFFAOYSA-N", category: "aryl halide" },
  { name: "苯肼", canonical: "NNc1ccccc1", inchiKey: "HKOOXMFOFWEVGF-UHFFFAOYSA-N", category: "amine" },
  { name: "N-甲基苯胺", canonical: "CNc1ccccc1", inchiKey: "AFBPFSWMIHJQDM-UHFFFAOYSA-N", category: "amine" },
  { name: "N,N-二甲基苯胺", canonical: "CN(C)c1ccccc1", inchiKey: "JLTDJTHDQAWBAV-UHFFFAOYSA-N", category: "amine" },
  { name: "苯甲酰胺", canonical: "NC(=O)c1ccccc1", inchiKey: "KXDAEFPNCMNJSK-UHFFFAOYSA-N", category: "amide" },
  { name: "苯甲腈", canonical: "N#Cc1ccccc1", inchiKey: "JFDZBHWFFUWGJE-UHFFFAOYSA-N", category: "nitrile" },
  { name: "硝基苯", canonical: "O=[N+]([O-])c1ccccc1", inchiKey: "LQNUZADURLCDLV-UHFFFAOYSA-N", category: "nitro" },
  { name: "苯甲醇钠/苄氧基", canonical: "[Na+].[O-]Cc1ccccc1", inchiKey: "LFQULJPVXNYWAG-UHFFFAOYSA-N", category: "misc" },
  { name: "4-羟基苯甲醛", canonical: "O=Cc1ccc(O)cc1", inchiKey: "RGHHSNMVTDWUBI-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "3,4-二甲氧基苯甲醛", canonical: "COc1ccc(C=O)cc1OC", inchiKey: "WJUFSDZVCOTFON-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "香草醛", canonical: "COc1cc(C=O)ccc1O", inchiKey: "MWOOGOJBHIARFG-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "苯乙醛", canonical: "O=CCc1ccccc1", inchiKey: "DTUQWGWMVIHBKE-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "苯丙酮", canonical: "CCC(=O)c1ccccc1", inchiKey: "KRIOVPPHQSLHCZ-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "4-哌啶酮", canonical: "O=C1CCNCC1", inchiKey: "VRJHQPZVIGNGMX-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "N-Boc-4-哌啶酮", canonical: "CC(C)(C)OC(=O)N1CCC(=O)CC1", inchiKey: "ROUYFJUVMYHXFJ-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "N-Boc-哌啶-4-甲酸", canonical: "CC(C)(C)OC(=O)N1CCC(C(=O)O)CC1", inchiKey: "JWOHBPPVVDQMKB-UHFFFAOYSA-N", category: "acid" },
  { name: "N-Boc-乙二胺", canonical: "CC(C)(C)OC(=O)NCCN", inchiKey: "AOCSUUGBCMTKJH-UHFFFAOYSA-N", category: "amine" },
  { name: "乙二胺", canonical: "NCCN", inchiKey: "PIICEJLVQHRZGT-UHFFFAOYSA-N", category: "amine" },
  { name: "1,3-丙二胺", canonical: "NCCCN", inchiKey: "XFNJVJPLKCPIBV-UHFFFAOYSA-N", category: "amine" },
  { name: "甲胺", canonical: "CN", inchiKey: "BAVYZALUXZFZLV-UHFFFAOYSA-N", category: "amine" },
  { name: "二甲胺", canonical: "CNC", inchiKey: "ROSDSFDQCJNGOL-UHFFFAOYSA-N", category: "amine" },
  { name: "氨", canonical: "N", inchiKey: "QGZKDVFQNNGYKY-UHFFFAOYSA-N", category: "amine" },
  { name: "苯磺酰氯", canonical: "O=S(=O)(Cl)c1ccccc1", inchiKey: "CSKNSYBAZOQPLR-UHFFFAOYSA-N", category: "sulfonyl" },
  { name: "苯硫酚", canonical: "Sc1ccccc1", inchiKey: "RMVRSNDYEFQCLF-UHFFFAOYSA-N", category: "thiol" },
  { name: "乙硫醇", canonical: "CCS", inchiKey: "DNJIEGIFACGWOD-UHFFFAOYSA-N", category: "thiol" },
  { name: "巯基乙酸", canonical: "O=C(O)CS", inchiKey: "CWERGRDVMFNCDR-UHFFFAOYSA-N", category: "thiol" },
  { name: "间氯过氧苯甲酸 mCPBA", canonical: "O=C(OO)c1cccc(Cl)c1", inchiKey: "NHQDETIJWKXCTC-UHFFFAOYSA-N", category: "oxidant" },
  { name: "戴斯-马丁试剂 DMP", canonical: "CC(=O)OI1(OC(C)=O)(OC(C)=O)OC(=O)c2ccccc21", inchiKey: "NKLCNNUWBJBICK-UHFFFAOYSA-N", category: "oxidant" },
  { name: "N-溴代丁二酰亚胺 NBS", canonical: "O=C1CCC(=O)N1Br", inchiKey: "PCLIMKBDDGJMGD-UHFFFAOYSA-N", category: "halogenating" },
  { name: "N-氯代丁二酰亚胺 NCS", canonical: "O=C1CCC(=O)N1Cl", inchiKey: "JRNVZBWKYDBUCA-UHFFFAOYSA-N", category: "halogenating" },
  { name: "N-碘代丁二酰亚胺 NIS", canonical: "O=C1CCC(=O)N1I", inchiKey: "LQZMLBORDGWNPD-UHFFFAOYSA-N", category: "halogenating" },
  { name: "四氯苯醌 / DDQ", canonical: "N#CC1=C(Cl)C(=O)C(C#N)=C(Cl)C1=O", inchiKey: "GLLMIZVPZWPYGP-UHFFFAOYSA-N", category: "oxidant" },
  { name: "4CzIPN", canonical: "N#Cc1c(-n2c3ccccc3c3ccccc32)c(-n2c3ccccc3c3ccccc32)c(C#N)c(-n2c3ccccc3c3ccccc32)c1-n1c2ccccc2c2ccccc21", inchiKey: "OYNJAUIAADXAOW-UHFFFAOYSA-N", category: "photocatalyst" },
  { name: "Mes-Acr+ (9-均三甲苯基吖啶鎓)", canonical: "Cc1cc(C)c(-c2c3ccccc3[n+](C)c3ccccc23)c(C)c1", inchiKey: "LULZXNOVLBISGB-UHFFFAOYSA-N", category: "photocatalyst" },
  { name: "曙红Y", canonical: "O=C([O-])c1ccccc1-c1c2cc(Br)c(=O)c(Br)c-2oc2c(Br)c([O-])c(Br)cc12", inchiKey: "AZXGXVQWEUFULR-UHFFFAOYSA-L", category: "photocatalyst" },
  { name: "玫瑰红 Rose Bengal", canonical: "O=C([O-])c1c(Cl)c(Cl)c(Cl)c(Cl)c1-c1c2cc(I)c(=O)c(I)c-2oc2c(I)c([O-])c(I)cc12", inchiKey: "VDNLFJGJEQUWRB-UHFFFAOYSA-L", category: "photocatalyst" },
  { name: "二苯基膦", canonical: "Pc1ccccc1", inchiKey: "RPGWZZNNEUHDAQ-UHFFFAOYSA-N", category: "phosphine" },
  { name: "三苯基膦", canonical: "c1ccc(P(c2ccccc2)c2ccccc2)cc1", inchiKey: "RIOQSEWOXXDEQQ-UHFFFAOYSA-N", category: "phosphine" },
  { name: "偶氮二甲酸二异丙酯 DIAD", canonical: "CC(C)OC(=O)N=NC(=O)OC(C)C", inchiKey: "VVWRJUBEIPHGQF-UHFFFAOYSA-N", category: "Mitsunobu" },
  { name: "苯基三氟硼酸钾", canonical: "F[B-](F)(F)c1ccccc1.[K+]", inchiKey: "DVAFPKUGAUFBTJ-UHFFFAOYSA-N", category: "boron" },
  { name: "碘化亚铜", canonical: "[Cu][I]", inchiKey: "LSXDOTMGLUJQCM-UHFFFAOYSA-M", category: "catalyst" },
  { name: "醋酸钯", canonical: "CC(=O)[O][Pd][O]C(C)=O", inchiKey: "YJVFFLUZDVXJQI-UHFFFAOYSA-L", category: "catalyst" },
  { name: "异丁基苯", canonical: "CC(C)Cc1ccccc1", inchiKey: "KXUHSQYYJYAXGZ-UHFFFAOYSA-N", category: "arene" },
  { name: "乙苯", canonical: "CCc1ccccc1", inchiKey: "YNQLUTRBYVCPMQ-UHFFFAOYSA-N", category: "arene" },
  { name: "二甲苯（对）", canonical: "Cc1ccc(C)cc1", inchiKey: "URLKBWYHVLBVBO-UHFFFAOYSA-N", category: "arene" },
  { name: "萘", canonical: "c1ccc2ccccc2c1", inchiKey: "UFWIBTONFRDIAS-UHFFFAOYSA-N", category: "arene" },
  { name: "联苯", canonical: "c1ccc(-c2ccccc2)cc1", inchiKey: "ZUOUZKKEUPVFJK-UHFFFAOYSA-N", category: "arene" },
  { name: "苯甲醚", canonical: "COc1ccccc1", inchiKey: "RDOXTESZEPMUJZ-UHFFFAOYSA-N", category: "arene" },
  { name: "水", canonical: "O", inchiKey: "XLYOFNOQVPJJNP-UHFFFAOYSA-N", category: "feedstock" },
  { name: "一氧化碳", canonical: "[C-]#[O+]", inchiKey: "UGFAIRIUMAVXCW-UHFFFAOYSA-N", category: "feedstock" },
  { name: "氢气", canonical: "[HH]", inchiKey: "UFHFLCQGNIYNRP-UHFFFAOYSA-N", category: "feedstock" },
  { name: "氧气", canonical: "O=O", inchiKey: "MYMOFIZGZYHOMD-UHFFFAOYSA-N", category: "feedstock" },
  { name: "二氧化碳", canonical: "O=C=O", inchiKey: "CURLTUGMZLYLDI-UHFFFAOYSA-N", category: "feedstock" },
  { name: "盐酸", canonical: "Cl", inchiKey: "VEXZGXHMUGYJMC-UHFFFAOYSA-N", category: "feedstock" },
  { name: "氢溴酸", canonical: "Br", inchiKey: "CPELXLSAUQHCOX-UHFFFAOYSA-N", category: "feedstock" },
  { name: "硫酸", canonical: "O=S(=O)(O)O", inchiKey: "QAOWNCQODCNURD-UHFFFAOYSA-N", category: "feedstock" },
  { name: "硝酸", canonical: "O=[N+]([O-])O", inchiKey: "GRYLNZFGIOXLOG-UHFFFAOYSA-N", category: "feedstock" },
  { name: "甲酸", canonical: "O=CO", inchiKey: "BDAGIHXWWSANSR-UHFFFAOYSA-N", category: "acid" },
  { name: "乙烯", canonical: "C=C", inchiKey: "VGGSQFUCUMXWEO-UHFFFAOYSA-N", category: "feedstock" },
  { name: "丙烯", canonical: "C=CC", inchiKey: "QQONPFPTGQHPMA-UHFFFAOYSA-N", category: "feedstock" },
  { name: "乙炔", canonical: "C#C", inchiKey: "HSFWRNGVRCDJHI-UHFFFAOYSA-N", category: "feedstock" },
  { name: "丁二烯", canonical: "C=CC=C", inchiKey: "KAKZBPTYRLMSJV-UHFFFAOYSA-N", category: "feedstock" },
  { name: "环戊二烯", canonical: "C1=CCC=C1", inchiKey: "ZSWFCLXCOIISFI-UHFFFAOYSA-N", category: "diene" },
  { name: "丙烯酸", canonical: "C=CC(=O)O", inchiKey: "NIXOWILDQLNWCW-UHFFFAOYSA-N", category: "Michael acceptor" },
  { name: "巴豆醛", canonical: "CC=CC=O", inchiKey: "MLUCVPSAIODCQM-UHFFFAOYSA-N", category: "Michael acceptor" },
  { name: "甲基丙烯酸甲酯", canonical: "C=C(C)C(=O)OC", inchiKey: "VVQNEPGJFQJSBK-UHFFFAOYSA-N", category: "Michael acceptor" },
  { name: "丁酮", canonical: "CCC(C)=O", inchiKey: "ZWEHNKRNPOVVGH-UHFFFAOYSA-N", category: "carbonyl" },
  { name: "异丙醇铝/异丙醇钠", canonical: "CC(C)[O-].[Na+]", inchiKey: "WBQTXTBONIWRGK-UHFFFAOYSA-N", category: "base" },
  { name: "乙醇钠", canonical: "CC[O-].[Na+]", inchiKey: "QDRKDTQENPPHOJ-UHFFFAOYSA-N", category: "base" },
  { name: "氢氧化钠", canonical: "[Na+].[OH-]", inchiKey: "HEMHJVSKTPXQMS-UHFFFAOYSA-M", category: "base" },
  { name: "氢氧化钾", canonical: "[K+].[OH-]", inchiKey: "KWYUFKZDYYNOTN-UHFFFAOYSA-M", category: "base" },
  { name: "碳酸钠", canonical: "O=C([O-])[O-].[Na+].[Na+]", inchiKey: "CDBYLPFSWZWCQE-UHFFFAOYSA-L", category: "base" },
  { name: "碳酸氢钠", canonical: "O=C([O-])O.[Na+]", inchiKey: "UIIMBOGNXHQVGW-UHFFFAOYSA-M", category: "base" },
  { name: "氯化亚砜", canonical: "O=S(Cl)Cl", inchiKey: "FYSNRJHAOHDILO-UHFFFAOYSA-N", category: "activating" },
  { name: "三氯氧磷", canonical: "O=P(Cl)(Cl)Cl", inchiKey: "XHXFXVLFKHQFAL-UHFFFAOYSA-N", category: "activating" },
  { name: "三溴化磷", canonical: "BrP(Br)Br", inchiKey: "IPNPIHIZVLFAFP-UHFFFAOYSA-N", category: "activating" },
  { name: "氯化铝", canonical: "[Cl][Al]([Cl])[Cl]", inchiKey: "VSCWAEJMTAWNJL-UHFFFAOYSA-K", category: "Lewis acid" },
  { name: "三氟化硼乙醚", canonical: "CCOCC.FB(F)F", inchiKey: "KZMGYPLQYOPHEL-UHFFFAOYSA-N", category: "Lewis acid" },
  { name: "氯化锌", canonical: "[Cl][Zn][Cl]", inchiKey: "JIAARYAFYJHUJI-UHFFFAOYSA-L", category: "Lewis acid" },
  { name: "四氯化钛", canonical: "[Cl][Ti]([Cl])([Cl])[Cl]", inchiKey: "XJDNKRIXUMDJCW-UHFFFAOYSA-J", category: "Lewis acid" },
  { name: "溴化苯镁（格氏）", canonical: "[Br][Mg][c]1ccccc1", inchiKey: "ANRQGKOBLBYXFM-UHFFFAOYSA-M", category: "organometallic" },
  { name: "甲基溴化镁", canonical: "[CH3][Mg][Br]", inchiKey: "AVFUHBJCUUTGCD-UHFFFAOYSA-M", category: "organometallic" },
  { name: "正丁基锂", canonical: "[Li][CH2]CCC", inchiKey: "MZRVEZGGRBJDDB-UHFFFAOYSA-N", category: "organometallic" },
  { name: "LDA", canonical: "CC(C)[N-]C(C)C.[Li+]", inchiKey: "ZCSHNCUQKCANBX-UHFFFAOYSA-N", category: "base" },
  { name: "LiHMDS", canonical: "C[Si](C)(C)[N-][Si](C)(C)C.[Li+]", inchiKey: "YNESATAKKCNGOF-UHFFFAOYSA-N", category: "base" },
  { name: "四氢铝锂", canonical: "[AlH4-].[Li+]", inchiKey: "OCZDCIYGECBNKL-UHFFFAOYSA-N", category: "reductant" },
  { name: "DIBAL-H", canonical: "CC(C)[CH2][AlH][CH2]C(C)C", inchiKey: "AZWXAPCAJCYGIA-UHFFFAOYSA-N", category: "reductant" },
  { name: "硼烷四氢呋喃", canonical: "B.C1CCOC1", inchiKey: "RMCYTHFAWCWRFA-UHFFFAOYSA-N", category: "reductant" },
  { name: "重铬酸吡啶盐 PCC", canonical: "[O]=[Cr](=[O])([O-])[Cl].c1cc[nH+]cc1", inchiKey: "LEHBURLTIWGHEM-UHFFFAOYSA-N", category: "oxidant" },
  { name: "高锰酸钾", canonical: "[K+].[O]=[Mn](=[O])(=[O])[O-]", inchiKey: "VZJVWSHVAAUDKD-UHFFFAOYSA-N", category: "oxidant" },
  { name: "过氧化氢", canonical: "OO", inchiKey: "MHAJPDPJQMAIIY-UHFFFAOYSA-N", category: "oxidant" },
  { name: "苯甲酸乙酯", canonical: "CCOC(=O)c1ccccc1", inchiKey: "MTZQAGJQAFMTAQ-UHFFFAOYSA-N", category: "ester" },
  { name: "对氨基苯甲酸", canonical: "Nc1ccc(C(=O)O)cc1", inchiKey: "ALYNCZNDIQEVRV-UHFFFAOYSA-N", category: "acid" },
  { name: "邻氨基苯甲酸", canonical: "Nc1ccccc1C(=O)O", inchiKey: "RWZYAGGXGHYGMB-UHFFFAOYSA-N", category: "acid" },
  { name: "水杨酸", canonical: "O=C(O)c1ccccc1O", inchiKey: "YGSDEFSMJLZEOE-UHFFFAOYSA-N", category: "acid" },
  { name: "对甲苯胺", canonical: "Cc1ccc(N)cc1", inchiKey: "RZXMPPFPUUCRFN-UHFFFAOYSA-N", category: "amine" },
  { name: "对氯苯胺", canonical: "Nc1ccc(Cl)cc1", inchiKey: "QSNSCYSYFYORTR-UHFFFAOYSA-N", category: "amine" },
  { name: "对甲氧基苯胺", canonical: "COc1ccc(N)cc1", inchiKey: "BHAAPTBBJKJZER-UHFFFAOYSA-N", category: "amine" },
  { name: "苯乙胺", canonical: "NCCc1ccccc1", inchiKey: "BHHGXPLMPWCGHP-UHFFFAOYSA-N", category: "amine" },
  { name: "环己胺", canonical: "NC1CCCCC1", inchiKey: "PAFZNILMFXTMIY-UHFFFAOYSA-N", category: "amine" },
  { name: "正丁胺", canonical: "CCCCN", inchiKey: "HQABUPZFAYXKJW-UHFFFAOYSA-N", category: "amine" },
];

/** InChIKey → 砌块。连接层（第一段 14 位）单独索引，用于忽略立体/盐型的宽松匹配。 */
export const BY_INCHIKEY = new Map(BUILDING_BLOCKS.map((block) => [block.inchiKey, block]));
export const BY_SKELETON = new Map(BUILDING_BLOCKS.map((block) => [block.inchiKey.split('-')[0], block]));

/**
 * 给提示词用的目录摘要：按类别分组的名称+SMILES。
 * 模型看得到我们有什么，才谈得上「拆到能买到的东西」。
 */
export function catalogDigest(): string {
  const groups = new Map<string, string[]>();
  for (const block of BUILDING_BLOCKS) {
    const list = groups.get(block.category) ?? [];
    list.push(`${block.name} ${block.canonical}`);
    groups.set(block.category, list);
  }
  return [...groups.entries()]
    .map(([category, items]) => `【${category}】${items.join('；')}`)
    .join('\n');
}
